# Generated by Codex on 2026-01-31

import uuid

from django.db import migrations, models
from django.db.models import Count


def populate_payment_ids(apps, schema_editor):
    Purchase = apps.get_model("purchases", "Purchase")

    duplicates = set(
        Purchase.objects.exclude(payment_id__isnull=True)
        .values("payment_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .values_list("payment_id", flat=True)
    )

    seen = set()
    if duplicates:
        for purchase in (
            Purchase.objects.filter(payment_id__in=duplicates)
            .order_by("id")
            .only("id", "payment_id")
        ):
            if purchase.payment_id in seen:
                purchase.payment_id = uuid.uuid4()
                purchase.save(update_fields=["payment_id"])
            else:
                seen.add(purchase.payment_id)

    for purchase in Purchase.objects.filter(payment_id__isnull=True).only("id", "payment_id"):
        purchase.payment_id = uuid.uuid4()
        purchase.save(update_fields=["payment_id"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="payment_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            code=populate_payment_ids,
            reverse_code=noop_reverse,
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
