# Generated by Django 5.2.9 on 2026-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="additional_materials",
            field=models.URLField(blank=True, null=True),
        ),
    ]

