# Generated by Django 5.2.10 on 2026-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_convert_course_prices_to_usd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='course',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
