# Generated by Django 5.2.9 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonprogress",
            name="last_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
