# Generated by Django 5.2.10 on 2026-03-09 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_merge_0004_and_0002_lesson_additional_materials'),
        ('entrance_tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancequizreward',
            name='reward_kind',
            field=models.CharField(choices=[('entrance_quiz', 'Entrance Quiz'), ('free_course_completion', 'Free Course Completion')], default='entrance_quiz', max_length=32),
        ),
        migrations.AddField(
            model_name='entrancequizreward',
            name='source_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_source_rewards', to='courses.course'),
        ),
        migrations.CreateModel(
            name='FreeCourseCompletionBenefitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_off', models.PositiveSmallIntegerField(default=10)),
                ('reward_ttl_hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_benefit_config', to='courses.course')),
            ],
            options={
                'verbose_name': 'Free Course Benefit Config',
                'verbose_name_plural': 'Free Course Benefit Configs',
                'ordering': ['source_course_id'],
            },
        ),
        migrations.CreateModel(
            name='FreeCourseCompletionBenefitClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_claims', to='entrance_tests.entrancequizreward')),
                ('source_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_course_benefit_claims', to='courses.course')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_free_course_claims', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_course_benefit_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'source_course')},
            },
        ),
    ]
