# Generated by Django 5.2.10 on 2026-03-09 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_merge_0004_and_0002_lesson_additional_materials'),
        ('entrance_tests', '0002_entrancequizreward_reward_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrancequizreward',
            unique_together={('user', 'course', 'reward_kind')},
        ),
        migrations.CreateModel(
            name='EntranceQuizBenefitClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance_quiz_claims', to='entrance_tests.entrancequizreward')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_quiz_benefit_claims', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_quiz_benefit_claim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntranceQuizGlobalAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_no', models.PositiveSmallIntegerField()),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('selected_answers', models.JSONField(blank=True, default=dict)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('score_percent', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrance_quiz_global_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'attempt_no')},
            },
        ),
    ]
